spring:
  application:
    name: demo
  data:
    mongodb:
      uri: mongodb://mongodb:27017/demo

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

demo:
  base-url: http://localhost:8080/

logging:
  level:
    "[org.springdoc]": DEBUG
    "[org.springframework.web]": INFO
